### ISSUE TITLE
Request: Invite Rewards

### ISSUE THREAD

**Issue by EZGraphics** [evanspy1/corebotaddons#1]
Hey, 3.0 update is taking way too long and I was wondering if anyone could make a Invite Rewards command for CoreBot and willing to share the code with the rest of us! Thank you so much.

**Comment by evanspy1** [comment]
Please be more specific, which command(s) would you like?  If you would just like the following commands I will work on them and/or contact a developer to work on them for you.  If there are any other commands you want, please respond and I'll add those to the list.
-invites / -invites <user>
-inviteleader

**Comment by EZGraphics** [comment]
-invites : tells them how many invites they have from {Fake, real, and bots}
-invitestop : Shows a leaderboard with the people with the top invites? (Maybe)
When someone hits a "milestone invite" it will post in a channel on the discord server and says they hit this many invites blah blah blah.. 
-invites (person) for Staff Members

**Comment by evanspy1** [comment]
The commands could definitely be done, I can't promise the milestone system.  Here is what I am going to condense it to:
-inviteleader - Top 10 invites
-invites - Users invites total (Bots, Fake, Real, Left)
-invites @username - Invites for that user (Bots, Fake, Real, Left)

**Comment by evanspy1** [comment]
A dev has been contacted with the appropriate information and will hopefully begin development tomorrow if everything goes as planned!

**Comment by evanspy1** [comment]
**CLOSED** - Added to offical corebot 3.0!
